# Generated by Django 2.2 on 2021-08-20 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=datetime.datetime(2021, 8, 20, 10, 24, 42, 11570, tzinfo=utc), verbose_name='保存日期')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
